name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2.4.2

      - name: Install PHP
        uses: shivammathur/setup-php@3eda58347216592f618bb1dff277810b6698e4ca # v2.19.1
        with:
          php-version: 8.1
          extensions: yaml

      - name: Install PHPUnit
        run: wget https://phar.phpunit.de/phpunit-9.5.phar

      - name: PHPUnit
        run: php phpunit-9.5.phar --verbose --colors=always
